# Generated by Django 4.1.4 on 2022-12-25 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0003_band_active_band_biography_band_genre_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="description",
            field=models.CharField(default="", max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="listing",
            name="sold",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="listing",
            name="type",
            field=models.CharField(
                choices=[
                    ("REC", "Records"),
                    ("CLO", "Clothing"),
                    ("POST", "Posters"),
                    ("MISC", "Miscellaneous"),
                ],
                default="MISC",
                max_length=10,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="listing",
            name="year",
            field=models.IntegerField(null=True),
        ),
    ]
